title: "My Classroom Results"
description: "A platform to check school results."
author: 
  social:
    facebook: "https://facebook.com/clemzclems"
    instagram: "https://instagram.com/clemzclems"
    twitter: "https://twitter.com/clemzclems"
    youtube: "https://youtube.com/"
    paypal: "https://paypal.me/clemzclems"
permalink: pretty
